### PR TITLE
Fixes for jQuery v3 compatibility

### PR DESCRIPTION
**Pull request by adambiggs**
jQuery v3.0.0 is now out, and there are some breaking changes that affect Spine.

The biggest change is that jQuery no longer has `bind()`/`unbind()` methods (they've been deprecated for some time now).

Spine has had `on()`/`off()` methods for a while as aliases, but I swapped this so that the core methods are named `on()`/`off()`, and they're aliased to `bind()`/`unbind()` for backward compatibility. IMO we should consider these aliases deprecated.

The other change is that jQuery's Promises are now compliant, which caused a few `Ajax` tests to fail because they relied on the jQuery's previous (incorrect) synchronous execution of promise callbacks.

**Disclaimer:** I won't be able to test this in the wild for some time since our app uses Bootstrap v3 (incompatible with jQuery v3).

### CODE REVIEW

**Comment by aeischeid** [comment]
THANKS! I was just thinking about needing to do this stuff the other day. We are also in a spot where testing this in the wild is a no-can-do in the short term, but I may have a sample app somewhere I can try things out on.

**Comment by aeischeid** [comment]
bind/unbind being deprecated like this is fine by me BTW.

Now that these ajax requests are promise A+ compliant I really need to set time aside to make all the spine model events return those promises.  That's gonna be a big deal!

**Comment by adambiggs** [comment]
> Now that these ajax requests are promise A+ compliant I really need to set time aside to make all the spine model events return those promises. That's gonna be a big deal!

My thoughts exactly! Too bad we can't upgrade to jQuery v3 in our app... But as long as we construct promises using a factory method, users of jQuery v2 can swap jQuery promises for something A+ compliant like Bluebird.

But at least jQuery v3 gives us a sane default Promise implementation without adding any other 3rd party dependencies to Spine core! Although maybe we should `console.warn()` users if they're using jQuery v2 promises...

**Comment by aeischeid** [comment]
BootStrap 3.3.7 supports jQuery3! time for me to get serious about this :)

**Comment by adambiggs** [comment]
Thanks for the heads up. I'll see if we can update to jQuery 3 in our app so these changes can be tested in the wild.

**Review by aeischeid — APPROVED** [review]
👍   :shipit:

**Review by aeischeid — APPROVED** [review]

**Pull request merged**
