### PR TITLE
Check if localStorage works when extending Model.Local

### PR DESCRIPTION
**Pull request by ins429**
https://github.com/spine/spine/issues/583.

This will check to see if localStorage is functional before extending `Spine.Model.Local`.

### CODE REVIEW

**Comment by aeischeid** [comment]
hm. is there as reason you didn't go with the seemingly simpler `if window.localStorage` check?

Curious what modernizr uses to check for this...

**Comment by ins429** [comment]
This is what modernizr using, https://github.com/Modernizr/Modernizr/blob/master/feature-detects/storage/localstorage.js#L37-L46.
When I tested on private Safari, `window.localStorage` is there but not functional.

**Comment by aeischeid** [comment]
okay, looks good. I might add a console log in the catch so developers would get some feedback on why it is not functioning now that the error will be swallowed up.

**Comment by ins429** [comment]
:+1:

**Pull request merged**
