### PR TITLE
model.replace add @$el = @el

### PR DESCRIPTION
**Pull request by Airead**
after call Model.replace(), @$el is not updated. This pull reques fix it.

### CODE REVIEW

**Comment by aeischeid** [comment]
in the controller constructor `@$el` is defined

    @el  = document.createElement(@tag) unless @el
    @el  = $(@el)
    @$el = @el

The bug is weird in that I would expect it should be just a reference to @el and I would expect @$el to work just fine, but what is also odd is that it is never used elsewhere in the source. I am tempted to think `@$el` is just something that we should get rid of. Why are you using @$el instead of @el?

**Comment by Airead** [comment]
I just think, $el hint that $el is a jquery object

**Comment by aeischeid** [comment]
My leaning is to remove `@$el` unless anyone is strongly opposed for some reason. I just don't see it as useful and don't suspect it is widely used since it isn't wel documented or anyhting. Instead of adding code to fix the bug feels better to remove the source of the problem. I can create an entry in the notes for 1.4 release that this reference is deprecated.

**Comment by Airead** [comment]
It's also Good idea.

**Pull request closed without merging**
