### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by 7rin0**
FIx not found dependencies: phantomjs-prebuilt and jasmine-core.
Tested on Ubuntu 15.10, node v5.8.0, npm 3.8.3.

### CODE REVIEW

**Comment by aeischeid** [comment]
looks to me like these should be 'devDependencies' instead. With that change I would be happy to bring this in!

**Comment by 7rin0** [comment]
@aeischeid you are right, since package.json was updated by "npm install {missing_package_name} --save" command it was added this way automatically. The update is done, but somehow `npm test` is failing on CircleCI. The error is not explicit and on local it works just fine.

**Comment by aeischeid** [comment]
not sure why the build is failing yet.

**Comment by 7rin0** [comment]
Just removed the last line, an empty one, to check again and tests are passing now...

**Comment by adambiggs** [comment]
Looks good, thanks @7rin0!

**Pull request merged**
