### PR TITLE
adds instance back to Class.ajaxSuccess args. addresses #573

### PR DESCRIPTION
**Pull request by aeischeid**
I can't really figure out why it was working as it did in Spine < 1.3.2 but this brings that back in a way. if we want it...

### CODE REVIEW

**Comment by cengebretson** [comment]
I think the model instance's trigger method added the `this` object to the arguments before calling the class trigger method. At least that was how it was done before. 

https://github.com/spine/spine/blob/b35f901836dd2de2a4a85e143b5bcec92bd4af2e/src/spine.coffee#L486

So something like this would make the events behave as before?

```
  trigger: ->
    Events.trigger.apply this, arguments
    return true if arguments[0] is 'refresh' # Don't trigger refresh events
    arguments.splice(1,0,this)
    @constructor.trigger arguments...
```

**Comment by aeischeid** [comment]
I tried a handful of things, but the new events system doesn't typically like the instance being spliced in like that. I can make it work that way only for ajaxSuccess of course:

```coffee
trigger: (args...)->
    # fire off the instance event
    Events.trigger.apply this, args
    return true if args[0] is 'refresh' # Don't trigger refresh events , because...
    args.splice(1, 0, this) if args[0] == 'ajaxSuccess'
    # fire off the class event
    @constructor.trigger args...
```

but that is not better than the change in the commit above really

**Comment by aeischeid** [comment]
hmmm... actually only `change` doesn't like item... this does alright.

``` coffee
trigger: (args...)->
    # fire off the instance event
    Events.trigger.apply this, args
    return true if args[0] is 'refresh' # Don't trigger refresh events , because...
    args.splice(1, 0, this) unless args[0] == 'change'
    # fire off the class event
    @constructor.trigger args...

**Comment by cengebretson** [comment]
looking a little more at the new events code it looks like the 'this' object is a part of the trigger call on most of the internal spine events, so `this` would be added twice in some cases with the suggestion I made above. Maybe it is simplest to just add it to the ajaxSuccess trigger.

**Pull request merged**
